### ISSUE TITLE
Mean Sea Level

### ISSUE THREAD

**Issue by martinjuckes** [cedadev/c3s_434_ecde_page_text#50] opened 2021-04-12 14:13 UTC
The sea level changes are, I think, all relative to mean sea level, rather than being relative to the local land surface. This is important because in some areas the coast is sinking or being up-lifted at rates which are comparable (e.g. East Anglia is sinking by about 30cm per century). To avoid confusion, I think the text should say explicitly that coastal subsidence and/or uplifting is not included in these figures.

**Comment by charliepascoe** [comment] 2021-04-12 20:06
Implemented in the spreadsheet and will be included in the next update.

"Projected changes in the mean sea level index are calculated relative to the mean of the mean sea level during the historical portion of this dataset which covers the period from 1977-2005. Storm surges caused by atmospheric forcing, and coastal subsidence and/or uplifting are not taken into account in the calculation of this index."

**Comment by charliepascoe** [comment] 2021-06-25 10:58
Updated the description with the following text:
Tidal dynamics, sea level change data from climate models, and large-scale long-term changes to land height due to post-glacial rebound are taken into account in the calculation of this index.

**Comment by charliepascoe** [comment] 2021-06-25 11:01
https://github.com/cedadev/c3s_434_ecde_page_text/commit/68ab06166f979ff5ef6ea14edc9f973a8a7eea6f
@sharppaul this is now ready to be published.

**Closed by charliepascoe** 2021-06-25 11:01 UTC
